[package]
name = "osl_derive"
version = "0.1.0"
authors = ["Anders Langlands <anderslanglands@gmail.com>"]
edition = "2018"

[dependencies]
quote = "0.6.12"
syn = "0.15.34"
osl = {path="../osl"}
proc-macro2="0.4"

[lib]
proc-macro = true
